# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevan Atkins | Composer and Sound Artist
email: kevan@kevanatkins.com
description: Composer and Sound Artist.
url: "http://kevanatkins.com" # the base hostname & protocol for your site
imgurl: "http://kevanatkins.com/images"

# Build settings
markdown: kramdown

collections:
  works:
    output: true
    permalink: /work/:title/
    date:
    subheadline:
    title:
    role:
    published:
    teaser:

gems:
  - jekyll-assets

assets:
  prefix: "/assets"
  assets:
    - "main.css"
  digest: true
  sources:
    - /assets/css
    - /assets/fonts
    - /assets/img
    - /assets/js
